name: Override Build Image for Master & Stable branches

on:
  push:
    branches:
      - aws-creds-test

jobs:
  # configure-aws-creds:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{ github.event.workflow_run.head_branch }}
  #     - name: AWS Configure
  #       uses: "./.github/template/aws-configure"
  #       with:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_REGION: us-west-1
  #     - name: Run pycodestyle on CodeBuild
  #       uses: aws-actions/aws-codebuild-run-build@v1
  #       with:
  #         project-name: aws-code-build-image-override
  configure-aws-creds:
    runs-on: ubuntu-latest
    steps:
      - name: AWS Configure
        uses: omanshgth/reusable_workflow@ref
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
      - name: Run pycodestyle on CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: aws-code-build-image-override